import Head from "next/head";
import styles from "../styles/Home.module.css";
import { compareDesc } from "date-fns";
import { useLiveReload } from "next-contentlayer/hooks";
import { allBlogs } from "contentlayer/generated";
import PostCard from "./components/ui/Postcard";

export function getStaticProps() {
  const blogs = allBlogs.sort((a, b) => {
    return compareDesc(new Date(a.date), new Date(b.date));
  });
  return { props: { blogs } };
}

function HomePage({ blogs }) {
  useLiveReload();
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-green-50">
      <Head>
        <title>AppWork: Redefining Multifamily Maintenance Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Simplify Multifamily Maintenance</h1>
        {blogs.map((blog, idx) => (
          <PostCard key={idx} {...blog} />
        ))}
      </main>
    </div>
  );
}
export default HomePage;
